apiVersion: v1
kind: Service
metadata:
  name: apimaterias
  labels:
    {{- include "materias.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: apimaterias
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - targetPort: 2999
      protocol: TCP
      name: http
      port: 2999