apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimaterias
  labels:
    {{- include "materias.labels" . | nindent 4 }}
    app.kubernetes.io/component: apimaterias
spec:
  replicas: {{ .Values.apimaterias.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: apimaterias
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apimaterias
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: apimaterias
          image: {{ .Values.apimaterias.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 2999
              protocol: TCP
          readinessProbe: 
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /apimaterias/v1/healthz
              port: 2999
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /apimaterias/v1/healthz
              port: 2999