apiVersion: v1
kind: Secret
metadata:
  name: mongomateriasdb
  labels:
    app.kubernetes.io/component: mongomateriasdb
    {{- include "materias.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_url: {{ .Values.mongoUrl | b64enc }}