apiVersion: v1
kind: Service
metadata:
  name: mongodbmaterias
  labels:
    {{- include "materias.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodbmaterias
spec:
  type: ClusterIP
  ports:
  - name: mongodbmaterias
    port: 27017
    targetPort: mongodbmaterias
  selector:
    app.kubernetes.io/name: mongodbmaterias
    app.kubernetes.io/instance: {{ .Release.Name }}